### ISSUE TITLE
P2P Receive Txs

### ISSUE THREAD

**Issue by jadwahab** [mrz1836/paymail-inspector#4]
**Is your feature request related to a problem? Please describe.**
`paymail-inspector` doesn't seem to support the [P2P Transactions](https://docs.moneybutton.com/docs/paymail-06-p2p-transactions.html) capability yet.

**Describe the solution you'd like**
Implementation of P2P txs capability.

**Describe alternatives you've considered**
I would be happy to implement it and submit a PR if you're open to that.

**Additional context**
Great work on the repo, it's looking very good!

**Comment by mrz1836** [comment]
That would be awesome @jadwahab! My long term goal was to use this to learn/explore paymail and then eventually break the `paymail` package out into its own standalone library.

Hit me up on slack in atlantis if you want to chat 😄

**Comment by mrz1836** [comment]
Closed via #5
